language: node_js
node_js:
  - "lts/*"
  - "node"
env:
  global:
    - CC_TEST_REPORTER_ID=97a75340b74bb5d9092724c8ffaa0fa7dc53e1c7d0dab51405f8766193925065
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
